import 'package:flutter/material.dart';

/// TODO: Add your color scheme here
/// This is a generated color scheme from the Material Theme Builder
/// To generated one, simply by going to the their website (https://m3.material.io/theme-builder#/custom)
/// Set your primary color
/// And that's it, now all you need to do is to export the scheme, by clicking export button on the top right and choose Flutter
/// Extract the zip file and copy the content of color_chemes.g.dart into this file

const lightColorScheme = ColorScheme(
  brightness: Brightness.light,
  primary: Color(0xFF006398),
  onPrimary: Color(0xFFFFFFFF),
  primaryContainer: Color(0xFFCDE5FF),
  onPrimaryContainer: Color(0xFF001D31),
  secondary: Color(0xFF51606F),
  onSecondary: Color(0xFFFFFFFF),
  secondaryContainer: Color(0xFFD4E4F6),
  onSecondaryContainer: Color(0xFF0D1D2A),
  tertiary: Color(0xFF67587A),
  onTertiary: Color(0xFFFFFFFF),
  tertiaryContainer: Color(0xFFEDDCFF),
  onTertiaryContainer: Color(0xFF221533),
  error: Color(0xFFBA1A1A),
  onError: Color(0xFFFFFFFF),
  errorContainer: Color(0xFFFFDAD6),
  onErrorContainer: Color(0xFF410002),
  outline: Color(0xFF72787E),
  background: Color(0xFFFCFCFF),
  onBackground: Color(0xFF1A1C1E),
  surface: Color(0xFFF9F9FC),
  onSurface: Color(0xFF1A1C1E),
  surfaceVariant: Color(0xFFDEE3EB),
  onSurfaceVariant: Color(0xFF42474E),
  inverseSurface: Color(0xFF2F3033),
  onInverseSurface: Color(0xFFF0F0F4),
  inversePrimary: Color(0xFF93CCFF),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF006398),
  outlineVariant: Color(0xFFC2C7CE),
  scrim: Color(0xFF000000),
);

const darkColorScheme = ColorScheme(
  brightness: Brightness.dark,
  primary: Color(0xFF93CCFF),
  onPrimary: Color(0xFF003351),
  primaryContainer: Color(0xFF004B74),
  onPrimaryContainer: Color(0xFFCDE5FF),
  secondary: Color(0xFFB8C8DA),
  onSecondary: Color(0xFF23323F),
  secondaryContainer: Color(0xFF394857),
  onSecondaryContainer: Color(0xFFD4E4F6),
  tertiary: Color(0xFFD2BFE7),
  onTertiary: Color(0xFF372A4A),
  tertiaryContainer: Color(0xFF4F4061),
  onTertiaryContainer: Color(0xFFEDDCFF),
  error: Color(0xFFFFB4AB),
  onError: Color(0xFF690005),
  errorContainer: Color(0xFF93000A),
  onErrorContainer: Color(0xFFFFDAD6),
  outline: Color(0xFF8C9198),
  background: Color(0xFF1A1C1E),
  onBackground: Color(0xFFE2E2E5),
  surface: Color(0xFF111416),
  onSurface: Color(0xFFC6C6C9),
  surfaceVariant: Color(0xFF42474E),
  onSurfaceVariant: Color(0xFFC2C7CE),
  inverseSurface: Color(0xFFE2E2E5),
  onInverseSurface: Color(0xFF1A1C1E),
  inversePrimary: Color(0xFF006398),
  shadow: Color(0xFF000000),
  surfaceTint: Color(0xFF93CCFF),
  outlineVariant: Color(0xFF42474E),
  scrim: Color(0xFF000000),
);
